on:
  push
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Firebase Functions
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.FUNCTION_URL }}
        method: 'GET'
