on:
  push
jobs:
  trigger-firebase-functions:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Firebase Functions
      id: getRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.FUNCTION_URL }}
        method: 'GET'
        timeout: 50000
    - name: Show Response
      run: |
        echo ${{ steps.getRequest.outputs.response }}
